<div class="modal fade bs-example-modal-lg2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" style="width:1500px;">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span><span class="sr-only">Close</span></button>
        			<h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-user"></span> Telemarketing</h4>
      			</div>
      			<div class="modal-body">
  				<iframe src="if.consultas" width="100%" height="700" frameborder="0" scrolling="no"></iframe>
			</div>
		</div>
	</div>
</div>