<script>
	if ( window.addEventListener ) {
		var state = 0, konami = [38,38,40,40,37,39,37,39,66,65];
		window.addEventListener("keydown", function(e) {
		if ( e.keyCode == konami[state] ) state++;
			else state = 0;
				if ( state == 10 )
					//$('#content').addClass('on');
					$('.panel-heading-btn').removeClass('off');
       		}, true);
	}
</script>

<style>
	.panel-heading-btn {
		-webkit-transition: all 5s ease;
		-moz-transition: all 5s ease;
		-ms-transition: all 5s ease;
		-o-transition: all 5s ease;
		transition: all 5s ease;
	}
	.off {
		opacity: 0.0;
	}

</style>

<!-- 
============ ID  ==========
444 = CAT
-->

	<!-- begin #page-loader -->
	<div id="page-loader" class="fade in"><span class="spinner"></span></div>
	<!-- end #page-loader -->
	
	<!-- begin #page-container -->
	<div id="page-container" class="fade page-without-sidebar page-header-fixed">


<!-- begin breadcrumb -->
			<ol class="breadcrumb pull-right">
				<li>
					<a href="secure/exit" class="btn btn-xs btn-danger" style="width:150px;">
						<i class="fa fa-key fa-2x pull-left"></i>
						<div style="height:10px;"></div>
							Cerrar Sesión
					</a>
				</li>
				<li class="active">&nbsp;</li>
			</ol>
			<!-- end breadcrumb -->
			<br>
			
	
		
		<!-- begin #content -->
		<div id="content" class="content">
			
			
		
<!-- -->
<div class="panel panel-inverse">
			    <div class="panel-heading">
			        <div class="panel-heading-btn off">
					<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand" data-original-title="" title=""><i class="fa fa-expand"></i></a>
					<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload" data-original-title="" title=""><i class="fa fa-repeat"></i></a>
                                	<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse" data-original-title="" title=""><i class="fa fa-minus"></i></a>
                                	<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                            	</div>
			        <h4 class="panel-title">Aplicaciones</h4>
			    </div>
			    <div class="panel-body">

<?php

	$permisos = $_SESSION['permisos'];
	# Equipo = 333

?>			    	
<div class="row">
	
<?php
	
	if ($permisos == '111' OR $permisos == '112' OR $permisos == '222' OR $permisos == '333' OR $permisos == '444' OR $permisos == '555' OR $permisos == '666' OR $permisos == '777' OR $permisos == '888' OR $permisos == '999') {

		include('view/v.open-01-directorio.phtml');
			
	}
	
	else {
	
	}	

	if ($permisos == '111' OR $permisos == '112' OR $permisos == '222' OR $permisos == '444' OR $permisos == '555' OR $permisos == '666' OR $permisos == '777' OR $permisos == '888' OR $permisos == '999') {
		include('view/v.open-01-ryg.phtml');
	}
	
	else {
	
	}
	
	if ($permisos == '444' OR $permisos == '666' OR $permisos == '777' OR $permisos == '888' OR $permisos == '999') {

		include('view/v.open-01-crm-cat.phtml');
	}
	
	else {
	
	}

	if ($permisos == '333' OR $permisos == '666' OR $permisos == '777' OR $permisos == '888' OR $permisos == '999') {

		include('view/v.open-01-crm-equipo.phtml');
	}
	
	else {
	
	}



	if ($permisos == '999') {

		include('view/v.open-01-cxc.phtml');
	}
	
	else {
	
	}	

	if ($permisos == '666' OR $permisos == '777' OR $permisos == '888' OR $permisos == '999') {

		include('view/v.open-01-crm-reclamaciones.phtml');
	}
	
	else {
	
	}

	if ($permisos == '111' OR $permisos == '112' OR $permisos == '222' OR $permisos == '333' OR $permisos == '444' OR $permisos == '555' OR $permisos == '666' OR $permisos == '777' OR $permisos == '888' OR $permisos == '999') {

		include('view/v.open-01-pac.phtml');
	}
	
	else {
	
	}


	if ($permisos == '111' OR $permisos == '222' OR $permisos == '444' OR $permisos == '666' OR $permisos == '777' OR $permisos == '888' OR $permisos == '999') {

		include('view/v.open-01-crm-consumibles.phtml');
	}
	
	else {
	
	}

	if ($permisos == '555' OR $permisos == '666' OR $permisos == '888' OR $permisos == '999') {

		include('view/v.open-01-directorio-administrador.phtml');
			
	}
	
	else {
	
	}

	if ($permisos == '666' OR $permisos == '888' OR $permisos == '999') {

		include('view/v.open-01-logs.phtml');
	}
	
	else {
	
	}

	if ($permisos == '222' OR $permisos == '444' OR $permisos == '666' OR $permisos == '888' OR $permisos == '999') {

		include('view/v.open-01-tablas-comparativas.phtml');
	}
	
	else {
	
	}

?>

		<iframe src="http://www.banorte.com/portal/personas/home.web"  width="300" height="300" frameborder="1"></iframe>
		</div>
	</div><!-- end #content -->
</div><!-- end page container -->
<div id="konamiCode" class="konamiCode">
</div>