<style>

.hasDatepicker {
	display: inline-block;
}

img.ui-datepicker-trigger {
	cursor: pointer;
	display: inline-block;
	position: absolute;
	width: 16%;

}

</style>

<div class="row">
	<form action="controller/c.filtro.fecha.php" method="post" id="filtrarporfecha">
	<div class="col-md-1 col-lg-1">
		<strong>Desde:</strong>
	</div>
	<div class="col-md-3 col-lg-3">
		<div class="input-group input-group-md vista" id="campoparafecha">
			<input type="text" name="desde" onlyread="onlyread" class="form-control datepicker" id="datepickerDesde" placeholder="<?= $fecha_inicio_filtro ?>">
		</div>
	</div>
	<div class="col-md-1 col-lg-1">
		<strong>Hasta:</strong>
	</div>
	<div class="col-md-3 col-lg-3">
		<div class="input-group input-group-md vista" id="campoparafecha">
			<input type="text" name="hasta" onlyread="onlyread" class="form-control datepicker" id="datepickerHasta" placeholder="<?= $fecha_fin_filtro ?>">
		</div>
	</div>
	</form>
	<div class="col-md-2 col-lg-2">
		<button type="button" class="btn btn-default btn-md" onclick="document.getElementById('filtrarporfecha').submit();">
			<span class="glyphicon glyphicon-filter"></span> Filtrar
		</button>
	</div>
	<div class="col-md-2 col-lg-2">
		<form action="controller/c.filtro.fecha-reset.php" method="post" id="quitarfiltro">
			<button type="button" class="btn btn-default btn-md" onclick="document.getElementById('quitarfiltro').submit();">
				Ver Todos
			</button>
		</form>
	</div>
</div>