<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-2">
			<button type="button" class="btn btn-info btn-lg" aria-label="Left Align" style="cursor:default; width:200px;">
				<span class="glyphicon glyphicon-star" aria-hidden="true"></span> Frios: <?= $_SESSION['en_proceso'] ?>
			</button>
		</div>
		<div class="col-md-2">
			<button type="button" class="btn btn-warning btn-lg" aria-label="Left Align" style="cursor:default; width:200px;">
				<span class="glyphicon glyphicon-star" aria-hidden="true"></span> Tibios: <?= $_SESSION['aceptado'] ?>
			</button>
		</div>
		<div class="col-md-2">
			<button type="button" class="btn btn-danger btn-lg" aria-label="Left Align" style="cursor:default; width:200px;">
				<span class="glyphicon glyphicon-star" aria-hidden="true"></span> Calientes: <?= $_SESSION['rechazado'] ?>
			</button>
		</div>
		<div class="col-md-2">
			<button type="button" class="btn btn-primary btn-lg" aria-label="Left Align" style="cursor:default; width:200px;">
				<span class="glyphicon glyphicon-star" aria-hidden="true"></span> Facturados: <?= $_SESSION['cancelado'] ?>
			</button>
		</div>
		<div class="col-md-2">
			<button type="button" class="btn btn-default btn-lg" aria-label="Left Align" style="cursor:default; width:200px;">
				<span class="glyphicon glyphicon-star" aria-hidden="true"></span> Descartados: <?= $_SESSION['detenido'] ?>
			</button>
		</div>
		<div class="col-md-1"></div>
	</div>

	<br>
	<hr>
	<br>

	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<?php
			$elquesobra = 100 -  substr($_SESSION['porcentaje'], 0, 5)
			?>
			<div class="progress">
  				<div class="progress-bar" role="progressbar" aria-valuenow="<?=  substr($_SESSION['porcentaje'], 0, 5) ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?=  substr($_SESSION['porcentaje'], 0, 5) ?>%;">
    					Eficiencia <?=  substr($_SESSION['porcentaje'], 0, 5) ?>%
				</div>
				<div class="progress-bar progress-bar-warning progress-bar-striped" style="width: <?= $elquesobra ?>%">
					<!-- active -->
					<span class="sr-only"></span>
				</div>
			</div>
		</div>
		<div class="col-md-3"></div>
	</div>
  </div>
</div>
</div>